### PR TITLE
Added Hover Effect in Skills Section

### PR DESCRIPTION
**Pull request by imniladri**

### CODE REVIEW

**Comment by imniladri** [comment]
Hello @danielbettech , I am facing a some issue in my hover effect (iconsHover.js)  with your fade / scroll in animation (scrollAnimations.js).
The fade in animation is not working!
Kindly, can you please help me?

image

**Comment by niloysikdar** [comment]
Hello @danielbettech ,  @imniladri  has done some hover effects on the skills section, but it is creating some issues with your fade-in animation, can you please look into this?

**Comment by danielbettech** [comment]
Hello @imniladri and @niloysikdar, of course. I will take I look and let you know.

**Comment by danielbettech** [comment]
Hey @imniladri How can I see your code, can you please give more details on what you are trying to do?
I just tried hover animation with css and it worked.

Example code:

```diff
.skills .skill-content .skill {
  margin: 40px 35px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
+ transition: all 0.3s;
}

.skills .skill-content .skill:hover {
+ transform: scale(1.05);
}
```

**Comment by danielbettech** [comment]
Hey @imniladri I saw the Vercel preview of your hover effect, I see its working right now.

**Comment by imniladri** [comment]
Of course @danielbettech , 
If we use only css then scale animation will be same for all the icons (skills divs), I want that the hover element will scale up and others will scale down with grayscale filter,
And when we remove the cursor all the icons should scale to normal size ,i.e, 1 with no grayscale filter.
You can the (iconsHover.js) file as the hover effect done in js as I can't do it in css.
Hope you got it!
Let me know!

On Hover:
image
image

With No Hover / Normal:
image

**Comment by imniladri** [comment]
> Hey @imniladri I saw the Vercel preview of your hover effect, I see its working right now.

But sometimes its not working, 
When you scroll down up then you will notice it!

**Comment by danielbettech** [comment]
> When you scroll down up then you will notice it!

Ok, I can see the images just disappear when you scroll down and the go up again. This is really weird, I will try to check if I can see what's happening.

**Comment by imniladri** [comment]
> > When you scroll down up then you will notice it!
> 
> Ok, I can see the images just disappear when you scroll down and the go up again. This is really weird, I will try to check if I can see what's happening.

Yup, that's the issue,
Hope you can fix it!

**Comment by niloysikdar** [comment]
Hope we can fix that issue asap, else we just need proper CSS for transitions.

**Comment by niloysikdar** [comment]
@imniladri , I have solved all the conflicts, you just need to fix the fade-out issue for now :3

**Comment by niloysikdar** [comment]
@imniladri ,  Also please pull the skills_hover branch from your origin before making any further changes.

**Pull request closed without merging**
